### ISSUE TITLE
Missing/Insufficient Environment Vars and Links

### ISSUE THREAD

**Issue by ojjsaw** [openvinotoolkit/docker_ci#109]
Built using:
```
python3 docker_openvino.py build --package_url https://storage.openvinotoolkit.org/repositories/openvino/packages/2020.3.2/l_openvino_toolkit_data_dev_ubuntu18_p_2020.3.355.tgz
```
Then use it as base image for some other image.

"model_downloader" path missing in PYTHONPATH and PATH //unlike model_optimizer

(removed 2nd issue written earlier): my 11th Gen Rocket Lake doesn't have "/dev/dri" directory to run DLStreamer vaapih264enc  on Ubuntu20. Not in scope for this repo.

**Comment by ilya-naumov** [comment]
Hi @ojjsaw,
* `PYTHONPATH` and `PATH` variables are set inside a container using [setup environment script](https://github.com/openvinotoolkit/openvino/blob/master/scripts/setupvars/setupvars.sh). We discuss the ability to add Model Downloader paths to this script. We will also add a native environment to a container for future releases starting from 2022.1.
* We have [this configuration guide](https://github.com/openvinotoolkit/docker_ci/blob/master/configure_gpu_ubuntu20.md) for GPU. You can follow it to configure a container to use GPU capabilities.
