### ISSUE TITLE
Error in running the script docker_openvino.py with arg gen_dockerfile 

### ISSUE THREAD

**Issue by sumeethn** [openvinotoolkit/docker_ci#114]
Hi, 

I am running the command below in a virtual env to generate a dockerfile:

```
python3 docker_openvino.py gen_dockerfile --distribution dev --product_version 2020.4
```
And observe the following error:

`
Something goes wrong **FAILED** 
Traceback (most recent call last):
  File "docker_openvino.py", line 363, in <module>
    args = parse_args(name=os.path.basename(__file__), description=des)
  File "/home/tinkerdeep/workdir/docker_ci/utils/arg_parser.py", line 498, in parse_args
    if args.tag_postfix:
AttributeError: 'Namespace' object has no attribute 'tag_postfix'
`

I am looking to build a dockerfile using version 2020.3.2 for the targets CPU, GPU and MULTI:CPU, GPU using ubuntu18. Appreciate your help!

**Comment by generalova-kate** [comment]
Hi, sorry for this issue, the master was unstable yesterday. Please try again. In the future, I recommend using released tag to build special release version: https://github.com/openvinotoolkit/docker_ci/releases/tag/2020.3.2 
Use the following row to generate a Dockerfile for 2020.3.2 release with CPU, GPU support only:
`docker_openvino.py gen_dockerfile --distribution dev --product_version 2020.3.2 -os ubuntu18 -d cpu -d gpu`

**Comment by sumeethn** [comment]
Resolved, thanks for the fix and your quick response.
