### ISSUE TITLE
Issue running with GPU

### ISSUE THREAD

**Issue by ojjsaw** [openvinotoolkit/docker_ci#152]
When running any of data_dev, runtime ubuntu docker images for GPU python app this is the error I get.
```
RuntimeError: Failed to create plugin /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPUPlease, check your environment
[CLDNN ERROR]. clGetPlatformIDs error -1001
```
On my ubuntu20 host machine I installed openvino as well and it works just fine (no errors), only in docker images.
Note: i also tried to follow the steps in root and non-root (openvino) user listed here https://github.com/openvinotoolkit/docker_ci/blob/master/configure_gpu_ubuntu20.md and mounted --device /dev/dri
Can you please let me know how to go about debugging this?
Host Machine: ubuntu20
Processor info (`cat /proc/cpuinfo`) : 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz

**Comment by ojjsaw** [comment]
@generalova-kate can you please let me know whom to reach out to debug further or if they have been validated on iGPU e.g. TGL

**Comment by generalova-kate** [comment]
Hi, @ojjsaw did you use tgl specific image? Like this: docker pull openvino/ubuntu20_runtime:2021.4_tgl

**Comment by generalova-kate** [comment]
You can check GPU access via a sample with the command below: docker run -it -u 0 --device /dev/dri:/dev/dri  --rm openvino/ubuntu20_dev:2021.4_tgl
/bin/bash -c "apt update && apt install sudo && deployment_tools/demo/demo_security_barrier_camera.sh -d GPU -sample-options -no_show"

**Comment by generalova-kate** [comment]
Your error says that you don't have access to iGPU device. I think you should try an image with `tgl` tag and add `render` group to your container follow by https://github.com/openvinotoolkit/docker_ci/blob/master/configure_gpu_ubuntu20.md instruction.

**Comment by ojjsaw** [comment]
@generalova-kate Is TGL still applicable in this case? 11th Gen has a variant Rocket Lake for desktop from this year (my processor above) that has UHD 750 Graphics instead of Xe Graphics. https://ark.intel.com/content/www/us/en/ark/products/212279/intel-core-i7-11700-processor-16m-cache-up-to-4-90-ghz.html

**Comment by generalova-kate** [comment]
@ojjsaw sorry, I didn't check the version. You are right tgl image is incompatible with Rocket lake. If you want to try OV docker on your platform, you can build a docker image by yourself. Are you interesting? I can help with the correct driver and instruction to build an image with correct driver.

**Comment by generalova-kate** [comment]
@ojjsaw openvino will officially support Rocket lake after 2021.4.1 release. It will be in September.
