### ISSUE TITLE
how install git in dev image

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/docker_ci#19]
here are my steps:

$ docker run -it --device /dev/dri:/dev/dri --rm openvino/ubuntu18_dev:2021.1
[setupvars.sh] OpenVINO environment initialized
openvino@bea218b5b0ad:/opt/intel/openvino_2021.1.110$ git
bash: git: command not found
openvino@bea218b5b0ad:/opt/intel/openvino_2021.1.110$ apt-get update
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
openvino@bea218b5b0ad:/opt/intel/openvino_2021.1.110$ sudo apt-get update
bash: sudo: command not found

**Comment by dpigasin** [comment]
Hi @guoyejun 
Run container with -u root, install git then use docker commit to save your changes.

**Comment by guoyejun** [comment]
thanks
