### ISSUE TITLE
docker build not working for env distribution 

### ISSUE THREAD

**Issue by harelfar2** [openvinotoolkit/docker_ci#194]
Hi, 
I'm trying to build a docker image `dev` distribution parameter but it doesn't work (error message ahead). 

It worked for me with `runtime` distribution:
`python3 docker_openvino.py build --package_url https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4/l_openvino_toolkit_runtime_ubuntu18_p_2021.4.582.tgz --distribution runtime  -d cpu -os ubuntu18 --product_version 2021`

but this one didn't (see that it's identical to the previous command except for the `dev` in both url and distribution parameter): 
`python3 docker_openvino.py build --package_url https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4/l_openvino_toolkit_dev_ubuntu18_p_2021.4.582.tgz --distribution dev -d cpu -os ubuntu18 --product_version 2021`

The error message:

ERROR     The command '/bin/bash -xo pipefail -c ${PYTHON_VER} -m pip install --no-cache-dir cmake &&     ${PYTHON_VER} -m pip install --no-cache-dir -r ${INTEL_OPENVINO_DIR}/python/${PYTHON_VER}/requirements.txt &&     find "${INTEL_OPENVINO_DIR}/" -type f \( -name "*requirements.*" -o  -name "*requirements_ubuntu18.*" -o \( -name "*requirements*.in" -and -not -name "*requirements-tensorflow.in" \) \) -not -path "*/accuracy_checker/*" -not -path "*/post_training_optimization_tool/*" -not -path "*/python3*/*" -not -path "*/python2*/*" -print0 | xargs -t -0 -n1 ${PYTHON_VER} -m pip install --no-cache-dir -r' returned a non-zero code: 123
[2021-11-18 13:37:49] INFO      Build time: 4 minutes 47 seconds
[2021-11-18 13:37:49] ERROR     Error building Docker image ['ubuntu18_dev:2021', 'ubuntu18_dev:latest']
          | Traceback (most recent call last):
          |   File "docker_openvino.py", line 403, in <module>
          |     launcher.build()
          |   File "docker_openvino.py", line 182, in build
          |     raise FailedBuildError(f'Error building Docker image {self.args.tags}')
          | utils.exceptions.FailedBuildError: Error building Docker image ['ubuntu18_dev:2021', 'ubuntu18_dev:latest']

**Comment by ilya-naumov** [comment]
Hi @harelfar2,
Could you retry with Docker CI framework from the [releases/2021/4](https://github.com/openvinotoolkit/docker_ci/tree/releases/2021%2F4) branch? 
 
We will have some OpenVINO folder structure changes since 2022.1 release and the master branch of the docker_ci is targeting 2022.x releases. We will reflect this in the documentation.

**Comment by harelfar2** [comment]
Yes it worked. 
Thanks a lot for your help and the quick response
