### ISSUE TITLE
Built custom ubuntu18 image takes huge space

### ISSUE THREAD

**Issue by KodeWorker** [openvinotoolkit/docker_ci#215]
Hi there,

I tried to build a custom ubuntu18 image from souce ([6f60a7d](https://github.com/openvinotoolkit/openvino/commit/6f60a7d8f098c7cf3195ba96d964a11bf1babe55)).
The docker images takes 40G. Even if I cut off source code repo, it's still 14G.
This is relatively large compared to those released on [docker hub](https://hub.docker.com/u/openvino)

Is it possible to further reduce the size of built OpenVINO?

B.R.,
Kelvin

**Comment by ilya-naumov** [comment]
Hello @KodeWorker,
Sorry for the delay. This Docker image is mainly intended for OpenVINO development and contains OpenVINO, Open Model Zoo and OpenCV built from source code and installed dependencies. I scanned built image with the dive tool and the most largest parts are OpenVINO repo and build files (28 GB), Python packages (5,9 GB) and OpenCV built from source (4,2 GB).

Can you describe your use case? The image size can be reduced by removing components unnecessary for you (like OpenCV or installed ML frameworks: tensorflow, mxnet etc).

**Comment by KodeWorker** [comment]
Hi @ilya-naumov,

Thanks for your advices. 
In my use case, the docker image is only for converting ONNX model to OpenVINO IR.
Does it means that I can remove all the OpenModelZoo, built OpenCV and some of the Python packages?

B.R.,
Kelvin

**Comment by ilya-naumov** [comment]
Hi @KodeWorker,
I think yes, you don't need OpenCV and some other components for this task. Currently the custom Dockerfile supports building an image without OpenCV (more info in the [readme](https://github.com/openvinotoolkit/docker_ci/tree/master/dockerfiles/ubuntu20/build_custom#build-stages)) - this should reduce image size by about 4,2 GB: 
```
docker build --target openvino -t ubuntu20_custom_no_opencv:latest .
```

Another way to reduce the image size is to modify the Dockerfile manually. I created [this file](https://gist.github.com/ilya-naumov/872d6aacfaa3e300955366374f4c14b0) with the following changes:
1. Removed OpenVINO and OMZ source codes and build files, OMZ demos
2. Install ONNX-related Python dependencies only (I changed [this line](https://github.com/openvinotoolkit/docker_ci/blob/d0a8dc3c725eae45b2a6b04a9b39dcfd30797b35/dockerfiles/ubuntu20/build_custom/Dockerfile#L134)).
3. Removed OpenCV  

The resulting image takes (uncompressed) 6.4 GB versus 5.72 GB for `openvino/ubuntu20_dev:2021.4.2` from Docker Hub.

I think a good long term solution would be to add the ability (maybe build-arg) to build an image that doesn't include the repository files.

**Comment by ilya-naumov** [comment]
@KodeWorker You can also reduce the image size by building OpenVINO in Release configuration (instead of Debug specified by default). The CMake build options is specified in the [openvino_cmake.txt](https://github.com/openvinotoolkit/docker_ci/blob/master/dockerfiles/ubuntu20/build_custom/openvino_cmake.txt) file (more info can be found in the [wiki page](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux)) :
```
-D CMAKE_INSTALL_PREFIX=install

-D CMAKE_BUILD_TYPE=Release
-D ENABLE_PYTHON=ON
-D PYTHON_EXECUTABLE=/usr/bin/python3
-D ENABLE_WHEEL=ON
```

**Comment by KodeWorker** [comment]
Hi @ilya-naumov,

I build the image following your suggestion. The size of image is reduced to 1.88 G.
It is no longer an issue for me.
Thanks you so much :)

B.R.,
Kelvin
