### ISSUE TITLE
Problem with running docker build

### ISSUE THREAD

**Issue by zvif** [openvinotoolkit/docker_ci#25]
Hi,
I created a docker file successfully with the tool but get an error when running the build.

python docker_openvino.py gen_dockerfile -d cpu -os ubuntu20 --distribution runtime --product_version 2021.1
docker build . -t test_opnv_docker:1.0

I'm using Windows Powershell in 

Step 18/44 : RUN tar -xzf "${TEMP_DIR}"/*.tgz &&     OV_BUILD="$(find . -maxdepth 1 -type d -name "*openvino*" | grep -oP '(?<=_)\d+.\d+.\d+')" &&     OV_YEAR="$(find . -maxdepth 1 -type d -name "*openvino*" | grep -oP '(?<=_)\d+')" &&     OV_FOLDER="$(find . -maxdepth 1 -type d -name "*openvino*")" &&     mkdir -p /opt/intel/openvino_"$OV_BUILD"/ &&     cp -rf "$OV_FOLDER"/*  /opt/intel/openvino_"$OV_BUILD"/ &&     rm -rf "${TEMP_DIR:?}"/"$OV_FOLDER" &&     ln --symbolic /opt/intel/openvino_"$OV_BUILD"/ /opt/intel/openvino &&     ln --symbolic /opt/intel/openvino_"$OV_BUILD"/ /opt/intel/openvino_"$OV_YEAR" &&     rm -rf ${INTEL_OPENVINO_DIR}/deployment_tools/tools/workbench && rm -rf ${TEMP_DIR}
 ---> Running in e5c7dbb53a74
+ tar -xzf '/tmp/openvino_installer/*.tgz'
tar (child): /tmp/openvino_installer/*.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by generalova-kate** [comment]
Hi, @zvif please build the image with docker_openvino.py. It will create Docker file and then build the image with OpenVINO 2021.1 release inside.
` docker_openvino.py build -d cpu -os ubuntu20 --distribution runtime --product_version 2021.1`
if you want to run build directly by docker you need to specify --build-arg package_url=<URL with openvino package>

**Comment by zvif** [comment]
Thank you for pointing me in the right direction. There was still missing information (like the package url) but I managed to solve my problem. Just for anyone else who may have the challenge. I needed to create a docker file replacing the “FROM openvino/ubuntu20_runtime:2021.2" in my current docker file in order to use an OpenVino based solution. 
I did the following: 
1. docker_openvino.py build -d cpu -os ubuntu20 --distribution runtime --product_version 2021.2 
Under docker_ci-master\logs you can see the build data. If you open image_build.log you can see the build command 
2.  You can then take the docker file that was created, copy it to your project and modify it if needed. Remove the reference to the local directory. I needed to remove the product_name and then you can run the build command from the log in your project. This is my final command line: 
docker build --build-arg package_url=https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.2/l_openvino_toolkit_runtime_ubuntu20_p_2021.2.185.tgz  --build-arg GMMLIB=19.3.2 --build-arg IGC_CORE=1.0.2597 --build-arg IGC_OPENCL=1.0.2597 --build-arg INTEL_OPENCL=19.41.14441 --build-arg INTEL_OCLOC=19.41.14441 -t test_openv:1.1 -f openv.dockerfile .
