### ISSUE TITLE
cannot stat '/opt/intel/openvino/install_dependencies/97-myriad-usbboot.rules': No such file or directory

### ISSUE THREAD

**Issue by AndreaTantucci** [openvinotoolkit/docker_ci#270]
I am trying to build openvino runtime for VPU support using your script. These are my commands for generating and building the docker file 

`python3 docker_openvino.py gen_dockerfile -os ubuntu20 -dist runtime -d vpu -p 2022.1.0.643`

`python3 docker_openvino.py build --package_url https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.1/l_openvino_toolkit_runtime_ubuntu20_p_2022.1.0.643.tgz --file dockerfiles/ubuntu20/openvino_v_runtime_2022.1.0.643.dockerfile -t openvino_runtime:v1`

During the execution of the build there is an error in copying the file 97-myriad-usbboot.rules into the folder /etc/udev/rules.d.
Below the Dockerfile generated instructions where the error happens and the error in the log file

`WORKDIR /opt/libusb-1.0.22/
RUN /usr/bin/install -c -m 644 libusb-1.0.pc '/usr/local/lib/pkgconfig' && \
    cp ${INTEL_OPENVINO_DIR}/install_dependencies/97-myriad-usbboot.rules /etc/udev/rules.d/ && \
    ldconfig`

Error log:

`stream [91m+ cp /opt/intel/openvino/install_dependencies/97-myriad-usbboot.rules /etc/udev/rules.d/
[0m
stream [91mcp: cannot stat '/opt/intel/openvino/install_dependencies/97-myriad-usbboot.rules': No such file or directory
[0m
errorDetail {'code': 1, 'message': "The command '/bin/bash -xo pipefail -c /usr/bin/install -c -m 644 libusb-1.0.pc '/usr/local/lib/pkgconfig' &&     cp ${INTEL_OPENVINO_DIR}/install_dependencies/97-myriad-usbboot.rules /etc/udev/rules.d/ &&     ldconfig' returned a non-zero code: 1"}
error The command '/bin/bash -xo pipefail -c /usr/bin/install -c -m 644 libusb-1.0.pc '/usr/local/lib/pkgconfig' &&     cp ${INTEL_OPENVINO_DIR}/install_dependencies/97-myriad-usbboot.rules /etc/udev/rules.d/ &&     ldconfig' returned a non-zero code: 1
`

Can someone help me resolve this issue?

Moreover i added an instruction in the Dockerfile after the one reported above which i do not know if it is correct or not. I copied it from other examples in which support for GPU was built and translated into my case (i need vpu support).

`WORKDIR ${INTEL_OPENVINO_DIR}/install_dependencies
RUN ./install_NCS_udev_rules.sh --no_numa -y && \
    rm -rf /var/lib/apt/lists/*`

Can someone tells me if it is correct to put this instruction here or not? 

Thanks

**Comment by earcam** [comment]
Facing similar issue...

@AndreaTantucci you're using an old release; see https://storage.openvinotoolkit.org/repositories/openvino/packages/

... but I cannot find udev rules in latest 2022.3 

random download other release, and found it in:

l_openvino_toolkit_debian9_arm_2022.2.0.7713.af16ea1d79a_armhf/install_dependencies/97-myriad-usbboot.rules

**Comment by AndreaTantucci** [comment]
Hi @earcam. Yes i also verified on the official images available on Docker Hub and indeed for version 2022.2 the file in the _install dependencies_ directory. However since this repository also allows to generate dockerfiles for openvino 2022.1 i think it should be working also in that case which is not true.

Looking at the official image on docker hub i found that the udev_rules file is in the folder _/opt/intel/openvino_2022.1.0.643/runtime/3rdparty/_. 

For the latest release i red on the official web page that 2023.0 in not supporting MYRIAD yet. They will add this feature in the release 2023.1 (see https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-2022-3-lts-relnotes.html. They also suggest to use the release 2022.1 instead of 2022.2.

However i can consider this issue closed. Moreover i also suggest to modify the folder for the release 2022.1 since it is not working as expected.
