### ISSUE TITLE
Problem running hddl daemon

### ISSUE THREAD

**Issue by Gandio** [openvinotoolkit/docker_ci#28]
Hi.

I have installed the version 2020.4. The Installation of HDDL dependencies is sucessful, but when I reboot the PC and try to launch the daemon I get this error 

./bin/hddldaemon: error while loading shared libraries: libmvnc-hddl.so.0: cannot open shared object file: No such file or directory

Thanks

**Comment by generalova-kate** [comment]
Did you run setupvars.sh before run hddldaemon after reboot?

**Comment by generalova-kate** [comment]
No answer from the submitter. Out-dated. Closed.
