### ISSUE TITLE
ubuntu 20.04 requires non root user to be render group to use GPU acceleration

### ISSUE THREAD

**Issue by chungyehwangai** [openvinotoolkit/docker_ci#67]
Hi,

I want to use non-root user to use GPU plugin. And found /dev/dri is in render group. I found following links. So i added follow in dockerfile. On my fresh install ubuntu 20.04 desktop, render group id is 109.

RUN groupadd -g 109 render && \
    useradd -ms /bin/bash -G video,render,users openvino && \
    chown openvino -R /home/openvino

https://jellyfin.org/docs/general/administration/hardware-acceleration.html
...
VAAPI may require the render group added to the docker permissions. 
...

https://docs.unified-streaming.com/documentation/capture/media-sdk.html
...
Each non-root user which is supposed to be doing hardware transcoding must be made a member of the video and render groups.
...

Could you check to add openvino user to render group for non-root user to use GPU plugin?

Thanks and Regards,
Chungyeh

**Comment by generalova-kate** [comment]
Hi, @chungyehwangai  We know about this limitation, `render` group doesn't have a strong groupID like `video`, and we can't setup it during Docker build, but we will post instructions on how to fix it in the Dockerfile or Docker container in the next few days.

**Comment by chungyehwangai** [comment]
Thanks for the information. Looking forward to documentation update.

**Comment by generalova-kate** [comment]
Please read the instruction on how to configure a container in that case: https://github.com/openvinotoolkit/docker_ci/blob/master/configure_gpu_ubuntu20.md
