### ISSUE TITLE
lack of one backslash in templates/ubuntu20/install/install.dockerfile.j2

### ISSUE THREAD

**Issue by chungyehwangai** [openvinotoolkit/docker_ci#71]
Due to lack of one backslash in templates/ubuntu20/install/install.dockerfile.j2, it will causing error when build docker image with generated proprietary dockerfile.

RUN apt-get update && \
    apt-get install -y --no-install-recommends cpio && \
    rm -rf /var/lib/apt/lists/* && \
    tar -xzf ${TEMP_DIR}/*.tgz --strip 1 &&  <= missing backslash
    sed -i 's/decline/accept/g' silent.cfg && \
    ${TEMP_DIR}/install.sh -s silent.cfg && \

**Comment by generalova-kate** [comment]
@chungyehwangai Thanks for catching! @ilya-naumov please fix it ASAP.
