### ISSUE TITLE
Fully Enable HW acceleration on intel HW

### ISSUE THREAD

**Issue by fratealberto** [openvinotoolkit/docker_ci#75]
VAINFO and LIBVA are properly installed, but the following package is missing on ubuntu20dockerfile build (with openvino 2021.2)

apt install va-driver-all  OR  apt install intel-media-va-driver i965-va-driver

as a consequence vainfo and gst-inspect vaapi do not find relevant plugins for video HW encoding/decoding/postoprocess

It would be beneficial adding them in future releases

=O=O=

Minor remark: since images come with opencv pre-built, optionally add template file to build (and replace) OpenCV with contribs

Thank you for your excellent work
C.Alberto Avizzano

**Comment by generalova-kate** [comment]
Thanks for your observation. We added intel-media-va-driver-non-free to data_runtime Ubuntu 20 Docker image. It will be available soon with 2021.3 release. Now you can build your image based on the [Dockerfile](https://github.com/openvinotoolkit/docker_ci/blob/master/dockerfiles/ubuntu20/openvino_cgvh_data_runtime_2021.3.dockerfile)
About this topic "images come with opencv pre-built, optionally add template file to build (and replace) OpenCV with contribs" We added it to the backlog as a feature request.
